[package]
name = "web3_proxy"
version = "1.43.100"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

mimalloc = ["dep:mimalloc"]
rdkafka-src = ["dep:rdkafka", "rdkafka/cmake-build", "rdkafka/ssl-vendored"]
tests-needing-docker = []

[dependencies]
deduped_broadcast = { path = "../deduped_broadcast" }
latency = { path = "../latency" }

# TODO: regex has several "perf" features that we might want to use
anyhow = { version = "1.0.75", features = ["backtrace"] }
arc-swap = { version = "1.6.0" }
argh = "0.1.12"
async-stream = "0.3.5"
axum = { version = "0.6.20", features = ["headers", "tracing", "ws"] }
axum-client-ip = "0.4.2"
axum-macros = "0.3.8"
base64 = "0.21.5"
bytes = "1.5.0"
chrono = { version = "0.4.31", features = ["serde"] }
derivative = "2.2.0"
derive_more = { version = "0.99.17", features = ["nightly"] }
ethers = { version = "2.0.11", default-features = false, features = ["rustls", "ws"] }
fdlimit = "0.3.0"
fstrings = "0.2"
futures = { version = "0.3.29" }
futures-util = "0.3.29"
glob = "0.3.1"
handlebars = "4.5.0"
hashbrown = { version = "0.14.3", features = ["serde", "nightly"] }
hdrhistogram = "7.5.4"
hostname = "0.3.1"
http = "0.2.11"
hyper = { version = "0.14.27", features = ["full", "nightly"] }
itertools = "0.12.0"
listenfd = { version = "1.0.1", optional = true }
mimalloc = { version = "0.1.39", optional = true }
moka = { version = "0.12.1", default-features = false, features = ["atomic64", "future", "quanta"] }
nanorand = { version = "0.7.0", default-features = false, features = ["std", "tls", "wyrand"] }
num = { version = "0.4.1" }
num-traits = "0.2.17"
once_cell = { version = "1.18.0" }
ordered-float = {version = "4.2.0" }
pagerduty-rs = { version = "0.1.6", default-features = false, features = ["async", "rustls", "sync"] }
parking_lot = { version = "0.12.1", features = ["arc_lock", "nightly"] }
rdkafka = { version = "0.36.0", default-features = false, features = ["tokio", "tracing"], optional = true }
reqwest = { version = "0.11.22", default-features = false, features = ["json", "rustls", "stream"] }
sentry = { version = "0.31.8", default-features = false, features = ["anyhow", "backtrace", "contexts", "panic", "reqwest", "rustls", "serde_json", "tracing"] }
sentry-tracing = "0.31.8"
serde = { version = "1.0.193", features = ["rc"] }
serde-inline-default = "0.1.1"
serde_json = { version = "1.0.108", default-features = false, features = ["raw_value"] }
strum = { version = "0.25.0", features = ["derive"] }
time = { version = "0.3" }
tokio = { version = "1.34.0", features = ["full", "tracing"] }
tokio-stream = { version = "0.1.14", features = ["sync"] }
toml = "0.8.8"
tower-http = { version = "0.4.4", features = ["cors", "normalize-path", "sensitive-headers", "trace"] }
tower-layer = "0.3.2"
tower-service = "0.3.2"
tracing = "0.1"
ulid = { version = "1.1.0", features = ["rand", "uuid", "serde"] }
url = { version = "2.5.0" }

# TODO: why doesn't this work in dev-dependencies. i think because of how we split web3_proxy and web3_proxy_cli. im not sure that is even helping anymore
test-log = { version = "0.2.13", default-features = false, features = ["trace"] }

# # TODO: bring this back
# check-if-email-exists = "0.9.0"

[dev-dependencies]
env_logger = { version ="0.10", default-features = true, features = ["auto-color"] }
tokio = { version = "1.34.0", default-features = false, features = ["full", "test-util"] }
tracing = {version = "0.1", default-features = false}
tracing-subscriber = {version = "0.3", features = ["env-filter"]}
