[package]
name = "latency"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
portable-atomic = { version = "1.15.0", features = ["float"] }
serde = "1.0.229"
tokio = { version = "1.53.1", default-features = false, features = ["rt", "sync", "time"] }
tracing = { version = "0.1.44", default-features = false, features = ["std"] }
watermill = "0.1.2"

[dev-dependencies]
tokio = { version = "1.53.1", default-features = false, features = ["macros", "rt", "sync", "test-util", "time"] }
